# Generated by Django 4.2.7 on 2023-11-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('parol', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('semestr_id', models.CharField(max_length=255)),
                ('semestr_name', models.CharField(max_length=255)),
                ('semestr_code', models.CharField(max_length=255)),
                ('fakultet_id', models.CharField(max_length=255)),
                ('fakultet_name', models.CharField(max_length=255)),
                ('rasm', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
