# Generated by Django 4.2.7 on 2023-11-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kurs'),
        ),
    ]
