# Generated by Django 4.2.7 on 2023-11-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kurs',
            field=models.ForeignKey(default='1-kurs', on_delete=django.db.models.deletion.CASCADE, to='users.kurs'),
        ),
    ]
