# Generated by Django 4.2.7 on 2023-11-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Oqtuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.fan')),
            ],
        ),
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.fan')),
            ],
        ),
        migrations.CreateModel(
            name='Sorovnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.CharField(max_length=255)),
                ('oqtuvchi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.oqtuvchi')),
            ],
        ),
    ]
