# Generated by Django 4.2.7 on 2023-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baho', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.CharField(max_length=255)),
                ('fan', models.CharField(max_length=255)),
                ('tur', models.CharField(max_length=255)),
                ('oqtuvchi', models.CharField(max_length=255)),
                ('baho', models.CharField(max_length=255)),
            ],
        ),
    ]
