# Generated by Django 4.2.7 on 2023-11-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_kurs'),
        ('baho', '0004_sorovnoma_baza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Umumiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.fanlar')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kurs')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.oqituvchilar')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.turlar')),
            ],
        ),
        migrations.RemoveField(
            model_name='oqtuvchi',
            name='fan_id',
        ),
        migrations.RemoveField(
            model_name='oqtuvchi',
            name='kurs_id',
        ),
        migrations.RemoveField(
            model_name='oqtuvchi',
            name='tur_id',
        ),
        migrations.RemoveField(
            model_name='turi',
            name='fan_id',
        ),
        migrations.RemoveField(
            model_name='sorovnoma',
            name='oqtuvchi_id',
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Oqtuvchi',
        ),
        migrations.DeleteModel(
            name='Turi',
        ),
        migrations.AddField(
            model_name='sorovnoma',
            name='umumiy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baho.umumiy'),
            preserve_default=False,
        ),
    ]
