# Generated by Django 4.2.7 on 2023-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baho', '0005_fanlar_oqituvchilar_turlar_umumiy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorovnoma',
            name='baza',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
