# Generated by Django 4.2.7 on 2023-11-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baho', '0007_tur_oqituvchi_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='umumiy',
            name='baza',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
